import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import '@/styles/globals.css';

const popins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${popins.className} font-popins antialiased`}>
        {children}
      </body>
    </html>
  );
}
